version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_equip_manager
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: equip_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
